prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=1 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=2 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=3 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=4 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=5 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=6 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=7 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=8 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=9 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=10 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=11 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=12 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=13 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=14 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=15 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=16 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=17 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=18 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=19 --short_test=0
prefix_tune.py --dataset=Emotion --epochs=10 --lora_lr=0.001 --lr=0.01 --max_batch_size=32 --max_seq_len=96 --model_name=gpt2 --prefix_mode=Classic --prefix_size=10 --seed=20 --short_test=0